### PR TITLE
feat: Add enum to schema.

### PR DESCRIPTION
**Pull request by robinlinden**
This change is [Reviewable](https://reviewable.io/reviews/toktok/hs-schema/1)

### CODE REVIEW

**Comment by iphydf** [comment]
Can you add an example usage to the test?

**Comment by iphydf** [comment]
Also add an import for `(<*>)` to support ghc 7.8.4.

**Comment by robinlinden** [comment]
Sorry about the lack of updates on this. I'll add an example and the import either tomorrow or on the 2nd depending on how much time I can find for work around New Year's.

**Comment by iphydf** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/Data/Schema.hs, line 22 at r1](https://reviewable.io:443/reviews/toktok/hs-schema/1#-K_yqUQo9hFLbe90EVAQ:-K_yqUQo9hFLbe90EVAR:bg48qlo) ([raw file](https://github.com/toktok/hs-schema/blob/294e0aee134e88bed9fefa101614369934123cc8/src/Data/Schema.hs#L22)):*
> ```Haskell
> data Schema
>   = SchemaRecord [Field]
>   | SchemaEnum [Option]
> ```

Add an example usage to the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/hs-schema/1)*

**Review by iphydf — APPROVED** [review]

**Pull request merged**
